all:
  children:
    spark_cluster:
      hosts:
        spark-0:
          ansible_host: 192.168.0.194
          cluster_bond: 
            members:
              - enp1s0f0np0
              - enP2p1s0f0np0
              # - enp1s0f0np1
              # - enP2p1s0f0np1
            address: 172.16.0.1/30
            mtu: 9000
        spark-1:
          ansible_host: 192.168.0.221
          cluster_bond: 
            members:
              - enp1s0f0np0
              - enP2p1s0f0np0
              # - enp1s0f0np1
              # - enP2p1s0f0np1
            address: 172.16.0.2/30
            mtu: 9000
      vars:
        # Common variables for all spark nodes
        ansible_user: nvidia
        ansible_python_interpreter: /usr/bin/python3
        # SSH key configuration (run setup.yml first to generate the key)
        ansible_ssh_private_key_file: data/spark_cluster_key
